src/main/scala/uk/gov/hmrc/ct/HMRCAmendment.scala, src/main/scala/uk/gov/hmrc/ct/box/Types.scala, src/main/scala/uk/gov/hmrc/ct/box/retriever/FilingAttributesBoxValueRetriever.scala, src/test/scala/uk/gov/hmrc/ct/box/retriever/FilingAttributesBoxValueRetrieverSpec.scala, src/test/scala/uk/gov/hmrc/ct/computations/stubs/StubbedFilingAttributesBoxValueRetriever.scala, src/test/scala/uk/gov/hmrc/ct/version/calculations/ReturnVersionsCalculatorSpec.scala
Adding a flag to the filing attributes which determines if this is a HMRC Amendment.
=> CATO-1859 Allow amendments

src/main/scala/uk/gov/hmrc/ct/formats/package.scala
=> CATO-1859 User can make amendments to their past filings

src/main/scala/uk/gov/hmrc/ct/box/Types.scala, src/main/scala/uk/gov/hmrc/ct/ct600/v2/calculations/LoansToParticipatorsCalculator.scala, src/main/scala/uk/gov/hmrc/ct/ct600/v2/retriever/CT600BoxRetriever.scala, src/main/scala/uk/gov/hmrc/ct/ct600a/v2/A13.scala, src/main/scala/uk/gov/hmrc/ct/ct600a/v2/retriever/CT600ABoxRetriever.scala, src/test/scala/uk/gov/hmrc/ct/ct600/v2/calculations/LoansToParticipatorsCalculatorSpec.scala
It should never be a negative number and should not include A11 in the calculation.
=> CATO-3179 Fixed problem with calculation of A13.

src/main/scala/uk/gov/hmrc/ct/box/Types.scala, src/main/scala/uk/gov/hmrc/ct/ct600/v2/B1000.scala, src/main/scala/uk/gov/hmrc/ct/ct600/v2/B1001.scala, src/main/scala/uk/gov/hmrc/ct/ct600/v2/formats/package.scala, src/main/scala/uk/gov/hmrc/ct/ct600/v2/retriever/CT600BoxRetriever.scala, src/main/scala/uk/gov/hmrc/ct/ct600e/v2/E1012.scala, src/main/scala/uk/gov/hmrc/ct/ct600e/v2/retriever/CT600EBoxRetriever.scala, src/main/scala/uk/gov/hmrc/ct/ct600e/v3/E25.scala, src/main/scala/uk/gov/hmrc/ct/ct600e/v3/retriever/CT600EBoxRetriever.scala, src/main/scala/uk/gov/hmrc/ct/domain/CompanyTypes.scala, src/main/scala/uk/gov/hmrc/ct/version/calculations/ReturnVersionsCalculator.scala, src/test/scala/uk/gov/hmrc/ct/ct600e/v2/E1012Spec.scala, src/test/scala/uk/gov/hmrc/ct/ct600e/v3/E25Spec.scala, src/test/scala/uk/gov/hmrc/ct/version/calculations/ReturnVersionsCalculatorSpec.scala
1) Charities cannot have micro entity accounts
2) Charities cannot have joint filings
=> CATO-3051 Make some adjustments to the returns for charities

src/main/scala/uk/gov/hmrc/ct/accounts/AC12.scala, src/main/scala/uk/gov/hmrc/ct/box/ValidatableBox.scala, src/main/scala/uk/gov/hmrc/ct/computations/CP285.scala, src/main/scala/uk/gov/hmrc/ct/computations/calculations/AnnualInvestmentAllowanceCalculator.scala, src/main/scala/uk/gov/hmrc/ct/computations/calculations/ApportionedTurnoverCalculator.scala, src/main/scala/uk/gov/hmrc/ct/computations/calculations/LowEmissionCarsCalculator.scala, src/main/scala/uk/gov/hmrc/ct/computations/calculations/PoolPercentageCalculator.scala, src/main/scala/uk/gov/hmrc/ct/ct600/calculations/AccountingPeriodHelper.scala, src/main/scala/uk/gov/hmrc/ct/ct600/calculations/PeriodOfAccountsCalculator.scala, src/main/scala/uk/gov/hmrc/ct/ct600/v3/calculations/LoansToParticipatorsCalculator.scala, src/main/scala/uk/gov/hmrc/ct/ct600a/v2/LP02.scala, src/main/scala/uk/gov/hmrc/ct/ct600a/v2/LP03.scala, src/main/scala/uk/gov/hmrc/ct/ct600a/v3/LoansToParticipators.scala, src/main/scala/uk/gov/hmrc/ct/utils/DateImplicits.scala, src/main/scala/uk/gov/hmrc/ct/version/calculations/ReturnVersionsCalculator.scala, src/test/scala/uk/gov/hmrc/ct/accounts/AC12Spec.scala, src/test/scala/uk/gov/hmrc/ct/computations/calculations/ApportionedTurnoverCalculatorSpec.scala, src/test/scala/uk/gov/hmrc/ct/utils/DateImplicitsSpec.scala
Also brought Date Implicits into Calcs
=> Cato 3766 - AC12 validation for FRS 102 Abridged

src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC320A.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC5117.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC5121.scala, src/test/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC5117Spec.scala, src/test/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC5121Spec.scala
Should not allow values in AC5117 or AC5121 if AC43 is not provided.
=> CATO-4070 Added validation 

src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC116.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC117.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC120.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC121.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC126.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC130.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC18.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC19.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC20.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC21.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC30.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC31.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC34.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC35.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC470.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC471.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC58.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC59.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC64.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC65.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/abridged/AC66.scala, src/main/scala/uk/gov/hmrc/ct/box/Debit.scala
Plan on using this trait to identify boxes that should be renderer like (123) when positive.
=> CATO-4124 Added Debit trait to boxes as per ticket.

src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/ACQ5021.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/ACQ5022.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/ACQ5031.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/ACQ5032.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/ACQ5033.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/ACQ5034.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/ACQ5035.scala, src/test/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/ACQ5021Spec.scala, src/test/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/ACQ5022Spec.scala, src/test/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/ACQ5031Spec.scala, src/test/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/ACQ5032Spec.scala, src/test/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/ACQ5033Spec.scala, src/test/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/ACQ5034Spec.scala, src/test/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/ACQ5035Spec.scala
sooner or later I'm going to add a cannotHaveValueIF validation. I always make this mistake :)
=> CATO-4113 FULL (Lbs): updated validation

src/main/scala/uk/gov/hmrc/ct/accounts/frs102/retriever/FullAccountsBoxRetriever.scala
Whoops ... lesson from today - don't try to rush the PR.
=> CATO-3959: Fixing the retriever.

src/main/scala/uk/gov/hmrc/ct/accounts/frs102/AC8021.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC115.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC122.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC123.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC125.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC132.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC133.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC140.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC141.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC154.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC155.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC162.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC163.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC189.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC190.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC5052A.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC5058A.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC5064A.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/ACQ5021.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/ACQ5031.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs102/calculations/IntangibleAssetsCalculator.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/boxes/ACQ8161.scala, src/main/scala/uk/gov/hmrc/ct/box/retriever/BoxRetriever.scala, src/main/scala/uk/gov/hmrc/ct/ct600e/v3/calculations/IncomeCalculator.scala
added anyHaveValue utility method and refactoring
=> Cato 4220 added utility method

src/main/scala/uk/gov/hmrc/ct/accounts/frs102/boxes/AC140.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/boxes/AC8021.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/boxes/AC8023.scala, src/main/scala/uk/gov/hmrc/ct/accounts/frs10x/boxes/Directors.scala, src/test/scala/uk/gov/hmrc/ct/accounts/frs10x/boxes/DirectorsSpec.scala, src/test/scala/uk/gov/hmrc/ct/ct600/accounts/AC8021Spec.scala, src/test/scala/uk/gov/hmrc/ct/ct600/accounts/AC8023Spec.scala
Includes refactoring of validation of AC8021 and AC8023
=> CATO-4522 Fixing directors report validation

src/main/scala/uk/gov/hmrc/ct/accounts/AC12.scala, src/main/scala/uk/gov/hmrc/ct/ct600a/v3/A5.scala, src/main/scala/uk/gov/hmrc/ct/ct600a/v3/LPQ03.scala, src/main/scala/uk/gov/hmrc/ct/ct600a/v3/LPQ04.scala, src/main/scala/uk/gov/hmrc/ct/ct600a/v3/LPQ07.scala, src/main/scala/uk/gov/hmrc/ct/domain/CompanyTypes.scala, src/test/scala/uk/gov/hmrc/ct/accounts/AC12Spec.scala
AC12 should allow a max of £6,500,000 for charities.
=> CATO-4646 Fixed bug in AC12 validation

src/main/scala/uk/gov/hmrc/ct/ct600a/v3/LoansToParticipators.scala, src/test/scala/uk/gov/hmrc/ct/ct600/v3/LoansToParticipatorsSpec.scala
This had the side effect that  tax payable could be
negative when repayments after April '16 could be > loans
in that period as the relief is calculated with the higher
rate.
=> Validate that repayments/writeoffs after April '16 <= loans

src/main/scala/uk/gov/hmrc/ct/accounts/approval/retriever/HmrcAccountsApprovalBoxRetriever.scala, src/main/scala/uk/gov/hmrc/ct/box/ValidatableBox.scala, src/main/scala/uk/gov/hmrc/ct/computations/CP33.scala, src/test/scala/uk/gov/hmrc/ct/BoxValidationFixture.scala, src/test/scala/uk/gov/hmrc/ct/computations/CP33Spec.scala
Changes based on the CATO-4894 PR
=> CATO-4896V1

src/main/scala/uk/gov/hmrc/ct/computations/formats/package.scala, src/main/scala/uk/gov/hmrc/ct/computations/machineryAndPlant/CP105.scala, src/main/scala/uk/gov/hmrc/ct/computations/machineryAndPlant/CP109.scala, src/main/scala/uk/gov/hmrc/ct/computations/retriever/ComputationsBoxRetriever.scala, src/test/scala/uk/gov/hmrc/ct/computations/machineryAndPlant/MachineryAndPlantCalculatorLogicSpec.scala
Also contains changes of DLS-3788
=> DLS-3389 Update the M&P Summary page

src/main/scala/uk/gov/hmrc/ct/accounts/frs105/boxes/AC25.scala, src/test/scala/uk/gov/hmrc/ct/accounts/frs105/boxes/AC25Spec.scala
=> DLS-3832 Error message content is too long

src/main/scala/uk/gov/hmrc/ct/computations/CP983.scala, src/test/scala/uk/gov/hmrc/ct/computations/CP983Spec.scala
=> DLS-3896 The user cannot continue the journey even they completed the page on the trading account page

src/main/scala/uk/gov/hmrc/ct/computations/machineryAndPlant/CP105.scala, src/test/scala/uk/gov/hmrc/ct/computations/machineryAndPlant/MachineryAndPlantCalculatorLogicSpec.scala
Signed-off-by: Sean Murray <sean.murray@digital.hmrc.gov.uk>
=> [SM][LG][DLS-4139] Amended the calculation for CP105.

build.sbt, src/main/scala/uk/gov/hmrc/ct/CATO05.scala, src/main/scala/uk/gov/hmrc/ct/computations/formats/package.scala, src/main/scala/uk/gov/hmrc/ct/ct600/calculations/Ct600AnnualConstants.scala, src/main/scala/uk/gov/hmrc/ct/ct600/v3/B435.scala, src/main/scala/uk/gov/hmrc/ct/ct600/v3/calculations/MarginalRateReliefCalculatorV3.scala, src/main/scala/uk/gov/hmrc/ct/ct600/v3/retriever/CT600BoxRetriever.scala, src/main/scala/uk/gov/hmrc/ct/formats/package.scala, src/test/scala/uk/gov/hmrc/ct/ct600/calculations/Ct600AnnualConstantsSpec.scala, src/test/scala/uk/gov/hmrc/ct/ct600/v3/B326Spec.scala, src/test/scala/uk/gov/hmrc/ct/ct600/v3/stubs/StubbedCT600BoxRetriever.scala
[CATO] Marginal Rate Relief Validation calculation function to ct-calculations[CATO] Marginal Rate Relief Validation calculation function to ct-calculations
=> DLS-6674 DLS-6771 DLS-6699

src/main/scala/uk/gov/hmrc/ct/ct600/v3/calculations/LoansToParticipatorsCalculator.scala, src/main/scala/uk/gov/hmrc/ct/ct600a/v3/LoansToParticipators.scala, src/test/scala/uk/gov/hmrc/ct/ct600/v3/LoansToParticipatorsSpec.scala, src/test/scala/uk/gov/hmrc/ct/ct600/v3/calculations/LoansToParticipatorsCalculatorSpec.scala
Reverts hmrc/ct-calculations#705
=> Revert "DLS-7076 Adding new logic for loans to participators"

src/main/scala/uk/gov/hmrc/ct/ct600a/v3/LoansToParticipators.scala, src/test/scala/uk/gov/hmrc/ct/ct600/v3/LoansToParticipatorsSpec.scala
=> DLS- 7997 CATO To fix issue behind ‘sorry, we’re experiencing technical problems’ page

src/main/scala/uk/gov/hmrc/ct/ct600a/v3/LoansToParticipators.scala, src/test/scala/uk/gov/hmrc/ct/ct600/v3/LoansToParticipatorsSpec.scala
Fix to handle incorrect validation for loan amounts for before 2016/2022
=> DLS-8145 | Update error handling for invalid loan amounts

src/main/scala/uk/gov/hmrc/ct/version/calculations/ReturnVersionsCalculator.scala, src/test/scala/uk/gov/hmrc/ct/version/calculations/ReturnVersionsCalculatorSpec.scala
temporarily deactivating this condition
=> DLS-9085 CATO-Investigate and Resolve "Sorry we are having technical difficulties" Error during User Login

src/main/scala/uk/gov/hmrc/ct/ct600/v3/calculations/CorporationTaxCalculator.scala
=> DLS-9421 Customers being undercharged for partial years

build.sbt, src/main/scala/uk/gov/hmrc/ct/ct600/v3/B340.scala, src/main/scala/uk/gov/hmrc/ct/ct600/v3/B390.scala, src/main/scala/uk/gov/hmrc/ct/ct600/v3/calculations/CorporationTaxCalculator.scala, src/main/scala/uk/gov/hmrc/ct/ct600e/v3/E1005.scala, src/main/scala/uk/gov/hmrc/ct/ct600e/v3/E1015.scala, src/test/scala/uk/gov/hmrc/ct/ct600/v3/calculations/CorporationTaxCalculatorSpec.scala
=> DLS-9540 CATO- Companies being charged incorrect rates while straddlng multiple financial years

src/main/scala/uk/gov/hmrc/ct/CATO05.scala, src/main/scala/uk/gov/hmrc/ct/ct600/v3/B340.scala, src/main/scala/uk/gov/hmrc/ct/ct600/v3/B390.scala, src/main/scala/uk/gov/hmrc/ct/ct600/v3/calculations/CorporationTaxCalculator.scala, src/main/scala/uk/gov/hmrc/ct/ct600/v3/calculations/MarginalRateReliefCalculatorV3.scala, src/main/scala/uk/gov/hmrc/ct/ct600e/v3/E1005.scala, src/main/scala/uk/gov/hmrc/ct/ct600e/v3/E1015.scala, src/test/scala/uk/gov/hmrc/ct/ct600/v3/calculations/CorporationTaxCalculatorSpec.scala, src/test/scala/uk/gov/hmrc/ct/ct600/v3/calculations/MarginalRateReliefCalculatorV3Spec.scala
franked investment has been added to taxable
=> DLS-9642. Error Code: 9043 - company is unable to file their return
